baseurl = "https://dashboard.toniogela.dev/"
languageCode = "en"
title = "HomePage"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "RSS", "404", "page", "robotsTXT", "section"]

[params]
    name = "Dashboard"
    favicon = "favicon.png"
    greekFonts = false