baseurl = "https://dashboard.toniogela.dev/"
languageCode = "en"
title = "HomePage"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "RSS", "404", "page", "robotsTXT", "section"]

[params]
    name = "Dashboard"
    description = "TonioGela's Personal Dashboard"
    author = "Antonio Gelameris"
    greekFonts = false

    backgroundColor = "#4c566a"
    accentColor = "#2e3440"
    sectionTitleColor = "#2e3440"
    sectionTitleBackgroundColor = "#d8dee9cc"
    cardBackgroundColor = "#d8dee9"
    cardTitleColor = "#2e3440"
    bordersColor = "#2e3440"
    linkBackgroundColor = "#d8dee9"
    linkColor = "#2e3440"