title = "Dashboard"
base_url = "https://dashboard.toniogela.dev"
compile_sass = true
minify_html = true

[[extra.card]]
title = "GitHub"
img = "github.svg"
url = "https://github.com/TonioGela"

[[extra.card]]
title = "YouTube"
img = "youtube.svg"
url = "http://youtube.com"

[[extra.card]]
title = "Gmail"
img = "gmail.svg"
url = "https://www.gmail.com"

[[extra.card]]
title = "Whatsapp"
img = "whatsapp.svg"
url = "https://web.whatsapp.com/"

[[extra.card]]
title = "Telegram"
img = "telegram.svg"
url = "https://web.telegram.org/a/"

[[extra.card]]
title = "Hacker News"
img = "hackernews.svg"
url = "https://news.ycombinator.com"

[[extra.card]]
title = "Il Post"
img = "ilpost.svg"
url = "https://www.ilpost.it"

[[extra.card]]
title = "Linkedin"
img = "linkedin.svg"
url = "https://linkedin.com"
