baseurl = "https://dashboard.toniogela.dev/"
languageCode = "en"
title = "HomePage"
disableKinds = ["taxonomy", "taxonomyTerm", "sitemap", "RSS", "404", "page", "robotsTXT", "section"]

[params]
    name = "Dashboard"
    description = "TonioGela's Personal Dashboard"
    author = "Antonio Gelameris"
    greekFonts = false

    backgroundColor = "#182a41"
    accentColor = "black"
    sectionTitleColor = "black"
    sectionTitleBackgroundColor = "#f4f4f4cc"
    cardBackgroundColor = "white"
    cardTitleColor = "black"
    bordersColor = "black"
    linkBackgroundColor = "white"
    linkColor = "black"